version: '3'
services:
  wordpress:
    image: wordpress
    ports:
      - '80:80'
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: 'mysql:3306'
      WORDPRESS_DB_PASSWORD: password

  mysql:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
